version: "3.3"

services:
  db:
    build: ./postgres/
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - app-tier
  app :
    build: ./data_science_onboard/
    depends_on:
      - db      
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge